[package]
name = "my_array"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
log = { workspace = true }

[lib]
path = "lib.rs"
proc-macro = true
